TEMPLATE = """
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

// Generated by codegen from the schema's migration chain - do not edit.
// The ops the native file loader applies to an older file's embedded
// schema before matching it by name (docs/NATIVE_FILE_FORMAT_RESEARCH.md §4):
// every op of every migration past the file's version, in chain order.
// Ops name matching already covers (added/removed classes and fields,
// compatible retypes) aren't listed.

namespace {{schema.namespace}}::migrations
{
    enum class OpKind : uint8_t
    {
        RenameClass,     // old_name -> new_name (klass unused)
        RenameField,     // klass.old_name -> klass.new_name
        RenameEnumValue, // enum klass: old_name -> new_name
        Unsupported,     // needs the data runtime (not built yet): refuse the file
    };

    struct Op
    {
        std::string_view to_version; // the migration this op belongs to
        OpKind kind;
        std::string_view klass;
        std::string_view old_name;
        std::string_view new_name;
        std::string_view description; // the migration's
    };

    inline constexpr std::array<Op, {{ops | length}}> kOps{ {
    {%- for op in ops %}
        Op{ {{op.to_version}}, OpKind::{{op.kind}}, {{op.klass}}, {{op.old}}, {{op.new}}, {{op.description}} },
    {%- endfor %}
    } };
}
"""
