TEMPLATE = """
#pragma once
#include "root.hpp"
#include <cstddef>
#include <optional>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>

// Generated by codegen from the schema - do not edit.
// Compile-time tables the native file format (src/persistence) walks to
// save and load every pooled class and embedded struct without per-class
// hand-written code. Design: docs/NATIVE_FILE_FORMAT_RESEARCH.md §3.

namespace {{schema.namespace}}::native_tables
{
    /// @brief One stored field: its schema name and a pointer to the member.
    template <class Owner, class M>
    struct Member
    {
        using type = M;
        std::string_view name;
        M Owner::*ptr;
    };

    /// @brief Fields<T>::members - a tuple of Member for every stored field
    /// of a pooled XxxData or an embedded struct, in declaration order
    /// (child fields are derived from the index, never stored).
    template <class T>
    struct Fields;

    /// @brief Pooled<Tag> - one pooled class: its name, dense index,
    /// pool accessor, and list_order() (see below).
    template <class Tag>
    struct Pooled;

    /// @brief EnumInfo<E> - an enum's name and its value <-> name mapping
    /// (enums are stored by name, so renumbering one is harmless).
    template <class E>
    struct EnumInfo;

    inline constexpr std::size_t kPooledClassCount = {{schema.get_pool_classes() | length}};
{% for klass in schema.get_pool_classes() %}
    template <>
    struct Pooled<{{klass.name}}Tag>
    {
        using Data = {{klass.name}}Data;
        using Id = {{klass.name}}Id;
        static constexpr std::size_t index = {{loop.index0}};
        static constexpr std::string_view name = "{{klass.name}}";
        static Pool<{{klass.name}}Data, {{klass.name}}Id> &pool(Root &root) { return root.pool_{{klass.to_snake_case()}}(); }
        static const Pool<{{klass.name}}Data, {{klass.name}}Id> &pool(const Root &root) { return root.pool_{{klass.to_snake_case()}}(); }
        static void rebuild_index(Root &root, std::vector<std::string> &problems) { root.rebuild_{{klass.to_snake_case()}}_index(problems); }

        /// @brief Calls add(slot index) for every child in each parent's
        /// own child list, list by list, in list order - so saving rows in
        /// this order and rebuilding the index reproduces every list's
        /// order exactly.
        template <class Add>
        static void list_order([[maybe_unused]] const Root &root, [[maybe_unused]] Add &&add)
        {
        {%- for field in klass.get_parent_fields() %}
            {%- if field._parent_field.is_list %}
            root.pool_{{field._parent_klass.to_snake_case()}}().for_each_id([&]({{field._parent_klass.name}}Id parent) {
                for ({{klass.name}}Id child : root.get_{{field._parent_klass.to_snake_case()}}_{{field.parent}}(parent))
                    add(child.index);
            });
            {%- endif %}
        {%- endfor %}
        }
    };

    template <>
    struct Fields<{{klass.name}}Data>
    {
        static constexpr std::string_view name = "{{klass.name}}";
        static constexpr auto members = std::make_tuple(
        {%- for field in klass.get_struct_fields() %}
            Member<{{klass.name}}Data, decltype({{klass.name}}Data::{{field.name}})>{"{{field.name}}", &{{klass.name}}Data::{{field.name}}}{% if not loop.last %},{% endif %}
        {%- endfor %}
        );
    };
{% endfor %}
{%- for klass in schema.classes if not klass.has_pool and not klass.is_enum %}
    template <>
    struct Fields<{{klass.name}}>
    {
        static constexpr std::string_view name = "{{klass.name}}";
        static constexpr auto members = std::make_tuple(
        {%- for field in klass.get_struct_fields() %}
            Member<{{klass.name}}, decltype({{klass.name}}::{{field.name}})>{"{{field.name}}", &{{klass.name}}::{{field.name}}}{% if not loop.last %},{% endif %}
        {%- endfor %}
        );
    };
{% endfor %}
{%- for klass in schema.get_enums() %}
    template <>
    struct EnumInfo<{{klass.name}}>
    {
        static constexpr std::string_view name = "{{klass.name}}";
        static std::string to_name({{klass.name}} value) { return {{schema.namespace}}::to_string(value); }
        static std::optional<{{klass.name}}> from_name(std::string_view value) { return {{klass.to_snake_case()}}_from_string(value); }
    };
{% endfor %}
    /// @brief Calls f(Pooled<Tag>{}) for every pooled class, in dense-index order.
    template <class F>
    void for_each_pooled(F &&f)
    {
    {%- for klass in schema.get_pool_classes() %}
        f(Pooled<{{klass.name}}Tag>{});
    {%- endfor %}
    }
}
"""
