TEMPLATE = """
#pragma once
#include <cstddef>
#include <string_view>

// Generated by codegen from the schema - do not edit.
// See docs/NATIVE_FILE_FORMAT_RESEARCH.md §3 "Schema descriptor".

namespace {{schema.namespace}}::schema_info
{
    /// @brief Schema version string (Schema.version in schema.py).
    inline constexpr std::string_view kVersion = "{{version}}";

    /// @brief Hash of the schema's data shape (classes, fields, types,
    /// relations, enum values - not descriptions or TCL flags). Two builds
    /// with the same fingerprint store identical data.
    inline constexpr std::string_view kFingerprint = "{{fingerprint}}";

    /// @brief The full schema descriptor as compact JSON - copied verbatim
    /// into every native-format file so the file carries its own schema.
    inline constexpr std::string_view kDescriptorJson = R"{{delimiter}}({{descriptor_json}}){{delimiter}}";

    /// @brief One extension built in with a schema of its own: its package
    /// version (le_extension.toml), schema version, fingerprint and
    /// descriptor - recorded in every file holding its objects.
    struct ExtensionSchema
    {
        std::string_view name;
        std::string_view package_version;
        std::string_view version;
        std::string_view fingerprint;
        std::string_view descriptor_json;
    };

    /// @brief Every extension schema built in, in dependency order.
    inline constexpr ExtensionSchema kExtensions[] = {
{%- for ext in extensions %}
        {"{{ext.name}}", "{{ext.package_version}}", "{{ext.version}}", "{{ext.fingerprint}}", R"{{delimiter}}({{ext.descriptor_json}}){{delimiter}}"},
{%- endfor %}
        {}, // keeps the array non-empty; `name` is empty
    };
    inline constexpr std::size_t kExtensionCount = {{extensions|length}};
}
"""
