TEMPLATE = """
#pragma once
#include <string_view>

// Generated by codegen from the schema - do not edit.
// NATIVE_FILE_FORMAT_RESEARCH.md §3 "Schema descriptor".

namespace {{schema.namespace}}::schema_info
{
    /// @brief Schema version string (Schema.version in schema.py).
    inline constexpr std::string_view kVersion = "{{version}}";

    /// @brief Hash of the schema's data shape (classes, fields, types,
    /// relations, enum values - not descriptions or TCL flags). Two builds
    /// with the same fingerprint store identical data.
    inline constexpr std::string_view kFingerprint = "{{fingerprint}}";

    /// @brief The full schema descriptor as compact JSON - copied verbatim
    /// into every native-format file so the file carries its own schema.
    inline constexpr std::string_view kDescriptorJson = R"{{delimiter}}({{descriptor_json}}){{delimiter}}";
}
"""
