TEMPLATE = """#pragma once
// Generated by codegen from the schema's render= declarations (codegen --target
// render) - do not edit. The build regenerates it.
//
// Every class drawn in the Layout view through a Render declaration: the
// resolver gives each its own chunk per Layout, collect_dirty maps its
// changes to that chunk, and the Layout-view hit tests visit its shapes.
#include "database.hpp"
#include "generated/pipelines/view_layer_purpose.hpp"

#include <cstddef>
#include <string_view>

namespace {{namespace}}::renderable
{
{% for r in renderables %}
    /// @brief {{r.klass.name}}: its Shapes on {{r.purpose.name}}'s own row.
    struct {{r.klass.name}}Render
    {
        using Id = {{r.klass.name}}Id;
        static constexpr std::size_t index = {{loop.index0}};
        /// @brief Whether a Layout's objects are split into spatial tiles.
        static constexpr bool tiled = {{ 'true' if r.klass.render.tiled else 'false' }};
        static constexpr ChangeKlass klass = ChangeKlass::{{r.klass.name}};
        static constexpr ViewLayerPurpose purpose = ViewLayerPurpose::{{r.purpose.name}};
        /// @brief Its pseudo-row's name in the Layers panel.
        static constexpr std::string_view row_name = "{{r.purpose.name}}";
        /// @brief The Shape owner option naming it (Shape.{{r.owner_option}}).
        static constexpr std::string_view owner_option = "{{r.owner_option}}";

        static decltype(auto) in_layout(const Root &root, LayoutId layout) { return root.get_layout_{{r.layout_list}}(layout); }
        static decltype(auto) shapes(const Root &root, Id id) { return root.get_{{r.snake}}_{{r.shapes_list}}(id); }
        static Id owner_of(const ShapeData &shape) { return shape.{{r.owner_option}}(); }
        /// @brief The Layout an object is in (invalid if it's gone).
        static LayoutId layout_of(const Root &root, Id id)
        {
            const auto *object = root.get_{{r.snake}}(id);
            return object ? object->{{r.layout_field}} : LayoutId{};
        }
    };
{% endfor %}

    inline constexpr std::size_t kCount = {{renderables|length}};

    /// @brief Calls f(XRender{}) for each renderable class, in index order.
    template <class F>
    void for_each([[maybe_unused]] F &&f)
    {
{% for r in renderables %}
        f({{r.klass.name}}Render{});
{% endfor %}
    }
}
"""
