TEMPLATE = """#pragma once
// Generated by codegen from the schema's purposes (codegen --target render) -
// do not edit. The build regenerates it.
#include <array>
#include <cstddef>
#include <optional>
#include <string_view>

namespace {{namespace}}
{
    /// @brief What a ViewLayer represents: which kind of object drew the
    /// shapes on it. An application/rendering concept, not a LEF/DEF term.
    /// Ordinals cross the C API (le_purpose_at) within one process only;
    /// anything persisted refers to a purpose by label.
    enum class ViewLayerPurpose
    {
{% for p in purposes %}
        {{p.name}}, // {{p.description}}
{% endfor %}
    };

    inline constexpr std::size_t kViewLayerPurposeCount = {{purposes|length}};

    struct ViewLayerPurposeInfo
    {
        ViewLayerPurpose purpose;
        /// @brief The user-facing keyword (Tcl purpose commands, Layers panel).
        std::string_view label;
        bool visible_by_default;
        bool selectable_by_default;
        /// @brief Whether anything drawn on it can be selected at all.
        bool has_selectable_objects;
    };

    /// @brief Every purpose, indexed by ordinal.
    inline constexpr std::array<ViewLayerPurposeInfo, kViewLayerPurposeCount> kViewLayerPurposes{ {
{% for p in purposes %}
        {ViewLayerPurpose::{{p.name}}, "{{p.label}}", {{p.visible_by_default|lower}}, {{p.selectable_by_default|lower}}, {{p.has_selectable_objects|lower}}},
{% endfor %}
    } };

    constexpr const ViewLayerPurposeInfo &purpose_info(ViewLayerPurpose purpose)
    {
        return kViewLayerPurposes[static_cast<std::size_t>(purpose)];
    }

    /// @brief Whether anything drawn on `purpose` can ever be selected -
    /// false means its selectable toggle does nothing, so the Layers panel
    /// shows no checkbox for it.
    constexpr bool purpose_has_selectable_objects(ViewLayerPurpose purpose)
    {
        return purpose_info(purpose).has_selectable_objects;
    }

    /// @brief The purpose whose label is `label`, if any.
    constexpr std::optional<ViewLayerPurpose> purpose_from_label(std::string_view label)
    {
        for (const ViewLayerPurposeInfo &info : kViewLayerPurposes)
            if (info.label == label)
                return info.purpose;
        return std::nullopt;
    }
}
"""
