"""
le_project.lock: exactly what `le install` installed - each source's commit
and signer - so every machine builds the same thing. Written by `le install`
and `le update`, never by hand; commit it with le_project.toml.
"""

import hashlib
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

LOCK_FILE = "le_project.lock"
LOCK_FORMAT = 1


class LockError(Exception):
    pass


@dataclass
class LockedSource:
    source: str  # "github:owner/repo" or "path:/abs/dir"
    rev: Optional[str] = None  # the commit, for a github source
    signer: Optional[str] = None  # the signing key's fingerprint, for a github source
    unsigned: bool = False


@dataclass
class LockedExtension:
    name: str
    version: str
    tier: str  # "compiled" or "script"
    locked: LockedSource
    dependencies: List[str] = field(default_factory=list)


@dataclass
class Lock:
    project_hash: str
    layout_engine_version: str
    extension_api: int
    layout_engine: LockedSource
    extensions: List[LockedExtension] = field(default_factory=list)

    def extension(self, name: str) -> Optional[LockedExtension]:
        return next((e for e in self.extensions if e.name == name), None)


def project_hash(project_file: Path) -> str:
    return hashlib.sha256(project_file.read_bytes()).hexdigest()


def _string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _source_lines(locked: LockedSource) -> List[str]:
    lines = [f"source = {_string(locked.source)}"]
    if locked.rev:
        lines.append(f"rev = {_string(locked.rev)}")
    if locked.signer:
        lines.append(f"signer = {_string(locked.signer)}")
    if locked.unsigned:
        lines.append("unsigned = true")
    return lines


def dumps(lock: Lock) -> str:
    lines = [
        "# Generated by `le install` - do not edit. Commit it with le_project.toml.",
        f"format = {LOCK_FORMAT}",
        f"project_hash = {_string(lock.project_hash)}",
        "",
        "[layout_engine]",
        f"version = {_string(lock.layout_engine_version)}",
        f"extension_api = {lock.extension_api}",
        *_source_lines(lock.layout_engine),
    ]
    for e in lock.extensions:
        lines += [
            "",
            "[[extension]]",
            f"name = {_string(e.name)}",
            f"version = {_string(e.version)}",
            f"tier = {_string(e.tier)}",
            *_source_lines(e.locked),
            "dependencies = [" + ", ".join(_string(d) for d in e.dependencies) + "]",
        ]
    return "\n".join(lines) + "\n"


def _locked_source(table: dict) -> LockedSource:
    return LockedSource(source=table["source"], rev=table.get("rev"), signer=table.get("signer"), unsigned=table.get("unsigned", False))


def load(root: Path) -> Optional[Lock]:
    path = Path(root) / LOCK_FILE
    if not path.is_file():
        return None
    try:
        data = tomllib.loads(path.read_text())
        if data.get("format") != LOCK_FORMAT:
            raise LockError(f"{path}: unsupported lock format {data.get('format')!r}")
        le = data["layout_engine"]
        return Lock(
            project_hash=data["project_hash"],
            layout_engine_version=le["version"],
            extension_api=le["extension_api"],
            layout_engine=_locked_source(le),
            extensions=[
                LockedExtension(
                    name=e["name"],
                    version=e["version"],
                    tier=e["tier"],
                    locked=_locked_source(e),
                    dependencies=list(e.get("dependencies", [])),
                )
                for e in data.get("extension", [])
            ],
        )
    except (tomllib.TOMLDecodeError, KeyError) as e:
        raise LockError(f"{path}: {e!r} - delete it and run `le install` to recreate it") from e


def save(root: Path, lock: Lock) -> None:
    (Path(root) / LOCK_FILE).write_text(dumps(lock))
