# BUGS_AND_ENHANCEMENTS.md E26 - regenerates le_shell's own version/build-date
# header. Run via `${CMAKE_COMMAND} -P` from an `add_custom_target(... ALL ...)`
# (backend/CMakeLists.txt's own le_shell target) rather than at CMake configure
# time (a plain configure_file() call) specifically so the git hash and build
# date stay fresh on every *build*, not just every reconfigure - a custom
# target with no DEPENDS is always considered out of date, so this reruns
# every time `le_shell` is built, the same trick most real-world CMake
# projects embedding a git hash use. Expects -DSOURCE_DIR=... (the repo root
# `git describe`/`rev-parse` run against), -DPROJECT_VERSION=... (this
# project's own semver, from CMakeLists.txt's own `project(... VERSION ...)`)
# and -DOUTPUT_FILE=... (where to write the generated header) on the command
# line - a standalone `-P` script has no access to the parent CMakeLists.txt's
# own variables otherwise.

find_package(Git QUIET)

# "Official" release (E26's own wording) = the exact commit currently
# checked out is tagged - `git describe --tags --exact-match` only succeeds
# in that case, distinguishing a real tagged release from every other build
# (a local dev build, a CI build off a branch, ...), which instead falls
# back to the current short commit hash below. Neither call is fatal if git
# or the repo itself isn't available (e.g. a tarball source drop with no
# .git directory) - LE_SHELL_VERSION just falls back to "unknown" - a
# missing version banner shouldn't ever block a build.
set(LE_SHELL_VERSION "unknown")
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" describe --tags --exact-match HEAD
        RESULT_VARIABLE GIT_TAG_RESULT
        OUTPUT_QUIET
        ERROR_QUIET
    )
    if(GIT_TAG_RESULT EQUAL 0)
        set(LE_SHELL_VERSION "${PROJECT_VERSION}")
    else()
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short HEAD
            RESULT_VARIABLE GIT_HASH_RESULT
            OUTPUT_VARIABLE GIT_HASH
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        if(GIT_HASH_RESULT EQUAL 0 AND NOT GIT_HASH STREQUAL "")
            set(LE_SHELL_VERSION "${GIT_HASH}")
        endif()
    endif()
endif()

string(TIMESTAMP LE_SHELL_BUILD_DATE "%Y-%m-%d %H:%M:%S UTC" UTC)

get_filename_component(OUTPUT_DIR "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT_FILE}" "// Generated by cmake/generate_le_shell_version.cmake - do not edit, do not commit.
#pragma once
#define LE_SHELL_VERSION \"${LE_SHELL_VERSION}\"
#define LE_SHELL_BUILD_DATE \"${LE_SHELL_BUILD_DATE}\"
")
