// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library le.database;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



enum ViewType {
  Abstract(0),
  Layout(1),
  Schematic(2);

  final int value;
  const ViewType(this.value);

  factory ViewType.fromValue(int value) {
    switch (value) {
      case 0: return ViewType.Abstract;
      case 1: return ViewType.Layout;
      case 2: return ViewType.Schematic;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static ViewType? _createOrNull(int? value) =>
      value == null ? null : ViewType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<ViewType> reader = _ViewTypeReader();
}

class _ViewTypeReader extends fb.Reader<ViewType> {
  const _ViewTypeReader();

  @override
  int get size => 1;

  @override
  ViewType read(fb.BufferContext bc, int offset) =>
      ViewType.fromValue(const fb.Int8Reader().read(bc, offset));
}

class Database {
  Database._(this._bc, this._bcOffset);
  factory Database(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Database> reader = _DatabaseReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<Library>? get libraries => const fb.ListReader<Library>(Library.reader).vTableGetNullable(_bc, _bcOffset, 4);
  List<Design>? get designs => const fb.ListReader<Design>(Design.reader).vTableGetNullable(_bc, _bcOffset, 6);
  List<View>? get views => const fb.ListReader<View>(View.reader).vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'Database{libraries: ${libraries}, designs: ${designs}, views: ${views}}';
  }

  DatabaseT unpack() => DatabaseT(
      libraries: libraries?.map((e) => e.unpack()).toList(),
      designs: designs?.map((e) => e.unpack()).toList(),
      views: views?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, DatabaseT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class DatabaseT implements fb.Packable {
  List<LibraryT>? libraries;
  List<DesignT>? designs;
  List<ViewT>? views;

  DatabaseT({
      this.libraries,
      this.designs,
      this.views});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? librariesOffset = libraries == null ? null
        : fbBuilder.writeList(libraries!.map((b) => b.pack(fbBuilder)).toList());
    final int? designsOffset = designs == null ? null
        : fbBuilder.writeList(designs!.map((b) => b.pack(fbBuilder)).toList());
    final int? viewsOffset = views == null ? null
        : fbBuilder.writeList(views!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, librariesOffset);
    fbBuilder.addOffset(1, designsOffset);
    fbBuilder.addOffset(2, viewsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'DatabaseT{libraries: ${libraries}, designs: ${designs}, views: ${views}}';
  }
}

class _DatabaseReader extends fb.TableReader<Database> {
  const _DatabaseReader();

  @override
  Database createObject(fb.BufferContext bc, int offset) => 
    Database._(bc, offset);
}

class DatabaseBuilder {
  DatabaseBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addLibrariesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addDesignsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addViewsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DatabaseObjectBuilder extends fb.ObjectBuilder {
  final List<LibraryObjectBuilder>? _libraries;
  final List<DesignObjectBuilder>? _designs;
  final List<ViewObjectBuilder>? _views;

  DatabaseObjectBuilder({
    List<LibraryObjectBuilder>? libraries,
    List<DesignObjectBuilder>? designs,
    List<ViewObjectBuilder>? views,
  })
      : _libraries = libraries,
        _designs = designs,
        _views = views;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? librariesOffset = _libraries == null ? null
        : fbBuilder.writeList(_libraries!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? designsOffset = _designs == null ? null
        : fbBuilder.writeList(_designs!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? viewsOffset = _views == null ? null
        : fbBuilder.writeList(_views!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, librariesOffset);
    fbBuilder.addOffset(1, designsOffset);
    fbBuilder.addOffset(2, viewsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Library {
  Library._(this._bc, this._bcOffset);
  factory Library(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Library> reader = _LibraryReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'Library{id: ${id}, name: ${name}}';
  }

  LibraryT unpack() => LibraryT(
      id: id,
      name: name);

  static int pack(fb.Builder fbBuilder, LibraryT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class LibraryT implements fb.Packable {
  int id;
  String? name;

  LibraryT({
      this.id = 0,
      this.name});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    fbBuilder.startTable(2);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'LibraryT{id: ${id}, name: ${name}}';
  }
}

class _LibraryReader extends fb.TableReader<Library> {
  const _LibraryReader();

  @override
  Library createObject(fb.BufferContext bc, int offset) => 
    Library._(bc, offset);
}

class LibraryBuilder {
  LibraryBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class LibraryObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;

  LibraryObjectBuilder({
    int? id,
    String? name,
  })
      : _id = id,
        _name = name;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    fbBuilder.startTable(2);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Design {
  Design._(this._bc, this._bcOffset);
  factory Design(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Design> reader = _DesignReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get libraryId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'Design{id: ${id}, name: ${name}, libraryId: ${libraryId}}';
  }

  DesignT unpack() => DesignT(
      id: id,
      name: name,
      libraryId: libraryId);

  static int pack(fb.Builder fbBuilder, DesignT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class DesignT implements fb.Packable {
  int id;
  String? name;
  int libraryId;

  DesignT({
      this.id = 0,
      this.name,
      this.libraryId = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addUint32(2, libraryId);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'DesignT{id: ${id}, name: ${name}, libraryId: ${libraryId}}';
  }
}

class _DesignReader extends fb.TableReader<Design> {
  const _DesignReader();

  @override
  Design createObject(fb.BufferContext bc, int offset) => 
    Design._(bc, offset);
}

class DesignBuilder {
  DesignBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addLibraryId(int? libraryId) {
    fbBuilder.addUint32(2, libraryId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DesignObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;
  final int? _libraryId;

  DesignObjectBuilder({
    int? id,
    String? name,
    int? libraryId,
  })
      : _id = id,
        _name = name,
        _libraryId = libraryId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addUint32(2, _libraryId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class View {
  View._(this._bc, this._bcOffset);
  factory View(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<View> reader = _ViewReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  ViewType get type => ViewType.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 8, 0));
  int get designId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);
  List<Instance>? get instances => const fb.ListReader<Instance>(Instance.reader).vTableGetNullable(_bc, _bcOffset, 12);

  @override
  String toString() {
    return 'View{id: ${id}, name: ${name}, type: ${type}, designId: ${designId}, instances: ${instances}}';
  }

  ViewT unpack() => ViewT(
      id: id,
      name: name,
      type: type,
      designId: designId,
      instances: instances?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, ViewT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ViewT implements fb.Packable {
  int id;
  String? name;
  ViewType type;
  int designId;
  List<InstanceT>? instances;

  ViewT({
      this.id = 0,
      this.name,
      this.type = ViewType.Abstract,
      this.designId = 0,
      this.instances});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? instancesOffset = instances == null ? null
        : fbBuilder.writeList(instances!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(5);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addInt8(2, type.value);
    fbBuilder.addUint32(3, designId);
    fbBuilder.addOffset(4, instancesOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ViewT{id: ${id}, name: ${name}, type: ${type}, designId: ${designId}, instances: ${instances}}';
  }
}

class _ViewReader extends fb.TableReader<View> {
  const _ViewReader();

  @override
  View createObject(fb.BufferContext bc, int offset) => 
    View._(bc, offset);
}

class ViewBuilder {
  ViewBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addType(ViewType? type) {
    fbBuilder.addInt8(2, type?.value);
    return fbBuilder.offset;
  }
  int addDesignId(int? designId) {
    fbBuilder.addUint32(3, designId);
    return fbBuilder.offset;
  }
  int addInstancesOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ViewObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;
  final ViewType? _type;
  final int? _designId;
  final List<InstanceObjectBuilder>? _instances;

  ViewObjectBuilder({
    int? id,
    String? name,
    ViewType? type,
    int? designId,
    List<InstanceObjectBuilder>? instances,
  })
      : _id = id,
        _name = name,
        _type = type,
        _designId = designId,
        _instances = instances;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? instancesOffset = _instances == null ? null
        : fbBuilder.writeList(_instances!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(5);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addInt8(2, _type?.value);
    fbBuilder.addUint32(3, _designId);
    fbBuilder.addOffset(4, instancesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Instance {
  Instance._(this._bc, this._bcOffset);
  factory Instance(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Instance> reader = _InstanceReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get parentDesignId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get parentViewId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'Instance{id: ${id}, name: ${name}, parentDesignId: ${parentDesignId}, parentViewId: ${parentViewId}}';
  }

  InstanceT unpack() => InstanceT(
      id: id,
      name: name,
      parentDesignId: parentDesignId,
      parentViewId: parentViewId);

  static int pack(fb.Builder fbBuilder, InstanceT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class InstanceT implements fb.Packable {
  int id;
  String? name;
  int parentDesignId;
  int parentViewId;

  InstanceT({
      this.id = 0,
      this.name,
      this.parentDesignId = 0,
      this.parentViewId = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    fbBuilder.startTable(4);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addUint32(2, parentDesignId);
    fbBuilder.addUint32(3, parentViewId);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'InstanceT{id: ${id}, name: ${name}, parentDesignId: ${parentDesignId}, parentViewId: ${parentViewId}}';
  }
}

class _InstanceReader extends fb.TableReader<Instance> {
  const _InstanceReader();

  @override
  Instance createObject(fb.BufferContext bc, int offset) => 
    Instance._(bc, offset);
}

class InstanceBuilder {
  InstanceBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addParentDesignId(int? parentDesignId) {
    fbBuilder.addUint32(2, parentDesignId);
    return fbBuilder.offset;
  }
  int addParentViewId(int? parentViewId) {
    fbBuilder.addUint32(3, parentViewId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class InstanceObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;
  final int? _parentDesignId;
  final int? _parentViewId;

  InstanceObjectBuilder({
    int? id,
    String? name,
    int? parentDesignId,
    int? parentViewId,
  })
      : _id = id,
        _name = name,
        _parentDesignId = parentDesignId,
        _parentViewId = parentViewId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    fbBuilder.startTable(4);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addUint32(2, _parentDesignId);
    fbBuilder.addUint32(3, _parentViewId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Layer {
  Layer._(this._bc, this._bcOffset);
  factory Layer(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Layer> reader = _LayerReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  bool get visible => const fb.BoolReader().vTableGet(_bc, _bcOffset, 6, false);
  bool get selectable => const fb.BoolReader().vTableGet(_bc, _bcOffset, 8, false);
  String? get outlineColor => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  int get outlineWidth => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 12, 0);
  String? get fillColor => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 14);
  int get zindex => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 16, 0);

  @override
  String toString() {
    return 'Layer{name: ${name}, visible: ${visible}, selectable: ${selectable}, outlineColor: ${outlineColor}, outlineWidth: ${outlineWidth}, fillColor: ${fillColor}, zindex: ${zindex}}';
  }

  LayerT unpack() => LayerT(
      name: name,
      visible: visible,
      selectable: selectable,
      outlineColor: outlineColor,
      outlineWidth: outlineWidth,
      fillColor: fillColor,
      zindex: zindex);

  static int pack(fb.Builder fbBuilder, LayerT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class LayerT implements fb.Packable {
  String? name;
  bool visible;
  bool selectable;
  String? outlineColor;
  int outlineWidth;
  String? fillColor;
  int zindex;

  LayerT({
      this.name,
      this.visible = false,
      this.selectable = false,
      this.outlineColor,
      this.outlineWidth = 0,
      this.fillColor,
      this.zindex = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? outlineColorOffset = outlineColor == null ? null
        : fbBuilder.writeString(outlineColor!);
    final int? fillColorOffset = fillColor == null ? null
        : fbBuilder.writeString(fillColor!);
    fbBuilder.startTable(7);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addBool(1, visible);
    fbBuilder.addBool(2, selectable);
    fbBuilder.addOffset(3, outlineColorOffset);
    fbBuilder.addUint32(4, outlineWidth);
    fbBuilder.addOffset(5, fillColorOffset);
    fbBuilder.addUint32(6, zindex);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'LayerT{name: ${name}, visible: ${visible}, selectable: ${selectable}, outlineColor: ${outlineColor}, outlineWidth: ${outlineWidth}, fillColor: ${fillColor}, zindex: ${zindex}}';
  }
}

class _LayerReader extends fb.TableReader<Layer> {
  const _LayerReader();

  @override
  Layer createObject(fb.BufferContext bc, int offset) => 
    Layer._(bc, offset);
}

class LayerBuilder {
  LayerBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addVisible(bool? visible) {
    fbBuilder.addBool(1, visible);
    return fbBuilder.offset;
  }
  int addSelectable(bool? selectable) {
    fbBuilder.addBool(2, selectable);
    return fbBuilder.offset;
  }
  int addOutlineColorOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addOutlineWidth(int? outlineWidth) {
    fbBuilder.addUint32(4, outlineWidth);
    return fbBuilder.offset;
  }
  int addFillColorOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addZindex(int? zindex) {
    fbBuilder.addUint32(6, zindex);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class LayerObjectBuilder extends fb.ObjectBuilder {
  final String? _name;
  final bool? _visible;
  final bool? _selectable;
  final String? _outlineColor;
  final int? _outlineWidth;
  final String? _fillColor;
  final int? _zindex;

  LayerObjectBuilder({
    String? name,
    bool? visible,
    bool? selectable,
    String? outlineColor,
    int? outlineWidth,
    String? fillColor,
    int? zindex,
  })
      : _name = name,
        _visible = visible,
        _selectable = selectable,
        _outlineColor = outlineColor,
        _outlineWidth = outlineWidth,
        _fillColor = fillColor,
        _zindex = zindex;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? outlineColorOffset = _outlineColor == null ? null
        : fbBuilder.writeString(_outlineColor!);
    final int? fillColorOffset = _fillColor == null ? null
        : fbBuilder.writeString(_fillColor!);
    fbBuilder.startTable(7);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addBool(1, _visible);
    fbBuilder.addBool(2, _selectable);
    fbBuilder.addOffset(3, outlineColorOffset);
    fbBuilder.addUint32(4, _outlineWidth);
    fbBuilder.addOffset(5, fillColorOffset);
    fbBuilder.addUint32(6, _zindex);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Layers {
  Layers._(this._bc, this._bcOffset);
  factory Layers(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Layers> reader = _LayersReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<Layer>? get layers => const fb.ListReader<Layer>(Layer.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'Layers{layers: ${layers}}';
  }

  LayersT unpack() => LayersT(
      layers: layers?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, LayersT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class LayersT implements fb.Packable {
  List<LayerT>? layers;

  LayersT({
      this.layers});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? layersOffset = layers == null ? null
        : fbBuilder.writeList(layers!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, layersOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'LayersT{layers: ${layers}}';
  }
}

class _LayersReader extends fb.TableReader<Layers> {
  const _LayersReader();

  @override
  Layers createObject(fb.BufferContext bc, int offset) => 
    Layers._(bc, offset);
}

class LayersBuilder {
  LayersBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addLayersOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class LayersObjectBuilder extends fb.ObjectBuilder {
  final List<LayerObjectBuilder>? _layers;

  LayersObjectBuilder({
    List<LayerObjectBuilder>? layers,
  })
      : _layers = layers;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? layersOffset = _layers == null ? null
        : fbBuilder.writeList(_layers!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, layersOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Point {
  Point._(this._bc, this._bcOffset);
  factory Point(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Point> reader = _PointReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get x => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get y => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'Point{x: ${x}, y: ${y}}';
  }

  PointT unpack() => PointT(
      x: x,
      y: y);

  static int pack(fb.Builder fbBuilder, PointT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PointT implements fb.Packable {
  int x;
  int y;

  PointT({
      this.x = 0,
      this.y = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.startTable(2);
    fbBuilder.addInt32(0, x);
    fbBuilder.addInt32(1, y);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PointT{x: ${x}, y: ${y}}';
  }
}

class _PointReader extends fb.TableReader<Point> {
  const _PointReader();

  @override
  Point createObject(fb.BufferContext bc, int offset) => 
    Point._(bc, offset);
}

class PointBuilder {
  PointBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addX(int? x) {
    fbBuilder.addInt32(0, x);
    return fbBuilder.offset;
  }
  int addY(int? y) {
    fbBuilder.addInt32(1, y);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PointObjectBuilder extends fb.ObjectBuilder {
  final int? _x;
  final int? _y;

  PointObjectBuilder({
    int? x,
    int? y,
  })
      : _x = x,
        _y = y;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(2);
    fbBuilder.addInt32(0, _x);
    fbBuilder.addInt32(1, _y);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Polyline {
  Polyline._(this._bc, this._bcOffset);
  factory Polyline(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Polyline> reader = _PolylineReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<Point>? get points => const fb.ListReader<Point>(Point.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'Polyline{points: ${points}}';
  }

  PolylineT unpack() => PolylineT(
      points: points?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, PolylineT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PolylineT implements fb.Packable {
  List<PointT>? points;

  PolylineT({
      this.points});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? pointsOffset = points == null ? null
        : fbBuilder.writeList(points!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, pointsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PolylineT{points: ${points}}';
  }
}

class _PolylineReader extends fb.TableReader<Polyline> {
  const _PolylineReader();

  @override
  Polyline createObject(fb.BufferContext bc, int offset) => 
    Polyline._(bc, offset);
}

class PolylineBuilder {
  PolylineBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addPointsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PolylineObjectBuilder extends fb.ObjectBuilder {
  final List<PointObjectBuilder>? _points;

  PolylineObjectBuilder({
    List<PointObjectBuilder>? points,
  })
      : _points = points;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? pointsOffset = _points == null ? null
        : fbBuilder.writeList(_points!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, pointsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Rect {
  Rect._(this._bc, this._bcOffset);
  factory Rect(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Rect> reader = _RectReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Point? get ll => Point.reader.vTableGetNullable(_bc, _bcOffset, 4);
  Point? get ur => Point.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'Rect{ll: ${ll}, ur: ${ur}}';
  }

  RectT unpack() => RectT(
      ll: ll?.unpack(),
      ur: ur?.unpack());

  static int pack(fb.Builder fbBuilder, RectT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class RectT implements fb.Packable {
  PointT? ll;
  PointT? ur;

  RectT({
      this.ll,
      this.ur});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? llOffset = ll?.pack(fbBuilder);
    final int? urOffset = ur?.pack(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, llOffset);
    fbBuilder.addOffset(1, urOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'RectT{ll: ${ll}, ur: ${ur}}';
  }
}

class _RectReader extends fb.TableReader<Rect> {
  const _RectReader();

  @override
  Rect createObject(fb.BufferContext bc, int offset) => 
    Rect._(bc, offset);
}

class RectBuilder {
  RectBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLlOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addUrOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class RectObjectBuilder extends fb.ObjectBuilder {
  final PointObjectBuilder? _ll;
  final PointObjectBuilder? _ur;

  RectObjectBuilder({
    PointObjectBuilder? ll,
    PointObjectBuilder? ur,
  })
      : _ll = ll,
        _ur = ur;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? llOffset = _ll?.getOrCreateOffset(fbBuilder);
    final int? urOffset = _ur?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, llOffset);
    fbBuilder.addOffset(1, urOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Path {
  Path._(this._bc, this._bcOffset);
  factory Path(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Path> reader = _PathReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Polyline? get polyline => Polyline.reader.vTableGetNullable(_bc, _bcOffset, 4);
  int get width => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'Path{polyline: ${polyline}, width: ${width}}';
  }

  PathT unpack() => PathT(
      polyline: polyline?.unpack(),
      width: width);

  static int pack(fb.Builder fbBuilder, PathT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PathT implements fb.Packable {
  PolylineT? polyline;
  int width;

  PathT({
      this.polyline,
      this.width = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? polylineOffset = polyline?.pack(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, polylineOffset);
    fbBuilder.addInt32(1, width);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PathT{polyline: ${polyline}, width: ${width}}';
  }
}

class _PathReader extends fb.TableReader<Path> {
  const _PathReader();

  @override
  Path createObject(fb.BufferContext bc, int offset) => 
    Path._(bc, offset);
}

class PathBuilder {
  PathBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPolylineOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addWidth(int? width) {
    fbBuilder.addInt32(1, width);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PathObjectBuilder extends fb.ObjectBuilder {
  final PolylineObjectBuilder? _polyline;
  final int? _width;

  PathObjectBuilder({
    PolylineObjectBuilder? polyline,
    int? width,
  })
      : _polyline = polyline,
        _width = width;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? polylineOffset = _polyline?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, polylineOffset);
    fbBuilder.addInt32(1, _width);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Polygon {
  Polygon._(this._bc, this._bcOffset);
  factory Polygon(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Polygon> reader = _PolygonReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Polyline? get polyline => Polyline.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'Polygon{polyline: ${polyline}}';
  }

  PolygonT unpack() => PolygonT(
      polyline: polyline?.unpack());

  static int pack(fb.Builder fbBuilder, PolygonT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PolygonT implements fb.Packable {
  PolylineT? polyline;

  PolygonT({
      this.polyline});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? polylineOffset = polyline?.pack(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, polylineOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PolygonT{polyline: ${polyline}}';
  }
}

class _PolygonReader extends fb.TableReader<Polygon> {
  const _PolygonReader();

  @override
  Polygon createObject(fb.BufferContext bc, int offset) => 
    Polygon._(bc, offset);
}

class PolygonBuilder {
  PolygonBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addPolylineOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PolygonObjectBuilder extends fb.ObjectBuilder {
  final PolylineObjectBuilder? _polyline;

  PolygonObjectBuilder({
    PolylineObjectBuilder? polyline,
  })
      : _polyline = polyline;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? polylineOffset = _polyline?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, polylineOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Text {
  Text._(this._bc, this._bcOffset);
  factory Text(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Text> reader = _TextReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get label => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  Point? get location => Point.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'Text{label: ${label}, location: ${location}}';
  }

  TextT unpack() => TextT(
      label: label,
      location: location?.unpack());

  static int pack(fb.Builder fbBuilder, TextT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TextT implements fb.Packable {
  String? label;
  PointT? location;

  TextT({
      this.label,
      this.location});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? labelOffset = label == null ? null
        : fbBuilder.writeString(label!);
    final int? locationOffset = location?.pack(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, labelOffset);
    fbBuilder.addOffset(1, locationOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'TextT{label: ${label}, location: ${location}}';
  }
}

class _TextReader extends fb.TableReader<Text> {
  const _TextReader();

  @override
  Text createObject(fb.BufferContext bc, int offset) => 
    Text._(bc, offset);
}

class TextBuilder {
  TextBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLabelOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addLocationOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TextObjectBuilder extends fb.ObjectBuilder {
  final String? _label;
  final PointObjectBuilder? _location;

  TextObjectBuilder({
    String? label,
    PointObjectBuilder? location,
  })
      : _label = label,
        _location = location;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? labelOffset = _label == null ? null
        : fbBuilder.writeString(_label!);
    final int? locationOffset = _location?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, labelOffset);
    fbBuilder.addOffset(1, locationOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Shape {
  Shape._(this._bc, this._bcOffset);
  factory Shape(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Shape> reader = _ShapeReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get objectId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get label => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get layerName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  List<Rect>? get rects => const fb.ListReader<Rect>(Rect.reader).vTableGetNullable(_bc, _bcOffset, 10);
  List<Path>? get paths => const fb.ListReader<Path>(Path.reader).vTableGetNullable(_bc, _bcOffset, 12);
  List<Polygon>? get polygons => const fb.ListReader<Polygon>(Polygon.reader).vTableGetNullable(_bc, _bcOffset, 14);
  List<Text>? get texts => const fb.ListReader<Text>(Text.reader).vTableGetNullable(_bc, _bcOffset, 16);

  @override
  String toString() {
    return 'Shape{objectId: ${objectId}, label: ${label}, layerName: ${layerName}, rects: ${rects}, paths: ${paths}, polygons: ${polygons}, texts: ${texts}}';
  }

  ShapeT unpack() => ShapeT(
      objectId: objectId,
      label: label,
      layerName: layerName,
      rects: rects?.map((e) => e.unpack()).toList(),
      paths: paths?.map((e) => e.unpack()).toList(),
      polygons: polygons?.map((e) => e.unpack()).toList(),
      texts: texts?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, ShapeT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ShapeT implements fb.Packable {
  int objectId;
  String? label;
  String? layerName;
  List<RectT>? rects;
  List<PathT>? paths;
  List<PolygonT>? polygons;
  List<TextT>? texts;

  ShapeT({
      this.objectId = 0,
      this.label,
      this.layerName,
      this.rects,
      this.paths,
      this.polygons,
      this.texts});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? labelOffset = label == null ? null
        : fbBuilder.writeString(label!);
    final int? layerNameOffset = layerName == null ? null
        : fbBuilder.writeString(layerName!);
    final int? rectsOffset = rects == null ? null
        : fbBuilder.writeList(rects!.map((b) => b.pack(fbBuilder)).toList());
    final int? pathsOffset = paths == null ? null
        : fbBuilder.writeList(paths!.map((b) => b.pack(fbBuilder)).toList());
    final int? polygonsOffset = polygons == null ? null
        : fbBuilder.writeList(polygons!.map((b) => b.pack(fbBuilder)).toList());
    final int? textsOffset = texts == null ? null
        : fbBuilder.writeList(texts!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(7);
    fbBuilder.addUint32(0, objectId);
    fbBuilder.addOffset(1, labelOffset);
    fbBuilder.addOffset(2, layerNameOffset);
    fbBuilder.addOffset(3, rectsOffset);
    fbBuilder.addOffset(4, pathsOffset);
    fbBuilder.addOffset(5, polygonsOffset);
    fbBuilder.addOffset(6, textsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ShapeT{objectId: ${objectId}, label: ${label}, layerName: ${layerName}, rects: ${rects}, paths: ${paths}, polygons: ${polygons}, texts: ${texts}}';
  }
}

class _ShapeReader extends fb.TableReader<Shape> {
  const _ShapeReader();

  @override
  Shape createObject(fb.BufferContext bc, int offset) => 
    Shape._(bc, offset);
}

class ShapeBuilder {
  ShapeBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addObjectId(int? objectId) {
    fbBuilder.addUint32(0, objectId);
    return fbBuilder.offset;
  }
  int addLabelOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addLayerNameOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addRectsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addPathsOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addPolygonsOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addTextsOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ShapeObjectBuilder extends fb.ObjectBuilder {
  final int? _objectId;
  final String? _label;
  final String? _layerName;
  final List<RectObjectBuilder>? _rects;
  final List<PathObjectBuilder>? _paths;
  final List<PolygonObjectBuilder>? _polygons;
  final List<TextObjectBuilder>? _texts;

  ShapeObjectBuilder({
    int? objectId,
    String? label,
    String? layerName,
    List<RectObjectBuilder>? rects,
    List<PathObjectBuilder>? paths,
    List<PolygonObjectBuilder>? polygons,
    List<TextObjectBuilder>? texts,
  })
      : _objectId = objectId,
        _label = label,
        _layerName = layerName,
        _rects = rects,
        _paths = paths,
        _polygons = polygons,
        _texts = texts;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? labelOffset = _label == null ? null
        : fbBuilder.writeString(_label!);
    final int? layerNameOffset = _layerName == null ? null
        : fbBuilder.writeString(_layerName!);
    final int? rectsOffset = _rects == null ? null
        : fbBuilder.writeList(_rects!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? pathsOffset = _paths == null ? null
        : fbBuilder.writeList(_paths!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? polygonsOffset = _polygons == null ? null
        : fbBuilder.writeList(_polygons!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? textsOffset = _texts == null ? null
        : fbBuilder.writeList(_texts!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(7);
    fbBuilder.addUint32(0, _objectId);
    fbBuilder.addOffset(1, labelOffset);
    fbBuilder.addOffset(2, layerNameOffset);
    fbBuilder.addOffset(3, rectsOffset);
    fbBuilder.addOffset(4, pathsOffset);
    fbBuilder.addOffset(5, polygonsOffset);
    fbBuilder.addOffset(6, textsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BrowserPayload {
  BrowserPayload._(this._bc, this._bcOffset);
  factory BrowserPayload(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BrowserPayload> reader = _BrowserPayloadReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<LibraryInfo>? get libraries => const fb.ListReader<LibraryInfo>(LibraryInfo.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'BrowserPayload{libraries: ${libraries}}';
  }

  BrowserPayloadT unpack() => BrowserPayloadT(
      libraries: libraries?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, BrowserPayloadT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class BrowserPayloadT implements fb.Packable {
  List<LibraryInfoT>? libraries;

  BrowserPayloadT({
      this.libraries});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? librariesOffset = libraries == null ? null
        : fbBuilder.writeList(libraries!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, librariesOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'BrowserPayloadT{libraries: ${libraries}}';
  }
}

class _BrowserPayloadReader extends fb.TableReader<BrowserPayload> {
  const _BrowserPayloadReader();

  @override
  BrowserPayload createObject(fb.BufferContext bc, int offset) => 
    BrowserPayload._(bc, offset);
}

class BrowserPayloadBuilder {
  BrowserPayloadBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addLibrariesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BrowserPayloadObjectBuilder extends fb.ObjectBuilder {
  final List<LibraryInfoObjectBuilder>? _libraries;

  BrowserPayloadObjectBuilder({
    List<LibraryInfoObjectBuilder>? libraries,
  })
      : _libraries = libraries;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? librariesOffset = _libraries == null ? null
        : fbBuilder.writeList(_libraries!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, librariesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class LibraryInfo {
  LibraryInfo._(this._bc, this._bcOffset);
  factory LibraryInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<LibraryInfo> reader = _LibraryInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  List<DesignInfo>? get designs => const fb.ListReader<DesignInfo>(DesignInfo.reader).vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'LibraryInfo{id: ${id}, name: ${name}, designs: ${designs}}';
  }

  LibraryInfoT unpack() => LibraryInfoT(
      id: id,
      name: name,
      designs: designs?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, LibraryInfoT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class LibraryInfoT implements fb.Packable {
  int id;
  String? name;
  List<DesignInfoT>? designs;

  LibraryInfoT({
      this.id = 0,
      this.name,
      this.designs});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? designsOffset = designs == null ? null
        : fbBuilder.writeList(designs!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addOffset(2, designsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'LibraryInfoT{id: ${id}, name: ${name}, designs: ${designs}}';
  }
}

class _LibraryInfoReader extends fb.TableReader<LibraryInfo> {
  const _LibraryInfoReader();

  @override
  LibraryInfo createObject(fb.BufferContext bc, int offset) => 
    LibraryInfo._(bc, offset);
}

class LibraryInfoBuilder {
  LibraryInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addDesignsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class LibraryInfoObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;
  final List<DesignInfoObjectBuilder>? _designs;

  LibraryInfoObjectBuilder({
    int? id,
    String? name,
    List<DesignInfoObjectBuilder>? designs,
  })
      : _id = id,
        _name = name,
        _designs = designs;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? designsOffset = _designs == null ? null
        : fbBuilder.writeList(_designs!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addOffset(2, designsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DesignInfo {
  DesignInfo._(this._bc, this._bcOffset);
  factory DesignInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DesignInfo> reader = _DesignInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  List<ViewInfo>? get views => const fb.ListReader<ViewInfo>(ViewInfo.reader).vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'DesignInfo{id: ${id}, name: ${name}, views: ${views}}';
  }

  DesignInfoT unpack() => DesignInfoT(
      id: id,
      name: name,
      views: views?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, DesignInfoT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class DesignInfoT implements fb.Packable {
  int id;
  String? name;
  List<ViewInfoT>? views;

  DesignInfoT({
      this.id = 0,
      this.name,
      this.views});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? viewsOffset = views == null ? null
        : fbBuilder.writeList(views!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addOffset(2, viewsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'DesignInfoT{id: ${id}, name: ${name}, views: ${views}}';
  }
}

class _DesignInfoReader extends fb.TableReader<DesignInfo> {
  const _DesignInfoReader();

  @override
  DesignInfo createObject(fb.BufferContext bc, int offset) => 
    DesignInfo._(bc, offset);
}

class DesignInfoBuilder {
  DesignInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addViewsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DesignInfoObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;
  final List<ViewInfoObjectBuilder>? _views;

  DesignInfoObjectBuilder({
    int? id,
    String? name,
    List<ViewInfoObjectBuilder>? views,
  })
      : _id = id,
        _name = name,
        _views = views;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? viewsOffset = _views == null ? null
        : fbBuilder.writeList(_views!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addOffset(2, viewsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ViewInfo {
  ViewInfo._(this._bc, this._bcOffset);
  factory ViewInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ViewInfo> reader = _ViewInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'ViewInfo{id: ${id}, name: ${name}}';
  }

  ViewInfoT unpack() => ViewInfoT(
      id: id,
      name: name);

  static int pack(fb.Builder fbBuilder, ViewInfoT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ViewInfoT implements fb.Packable {
  int id;
  String? name;

  ViewInfoT({
      this.id = 0,
      this.name});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    fbBuilder.startTable(2);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ViewInfoT{id: ${id}, name: ${name}}';
  }
}

class _ViewInfoReader extends fb.TableReader<ViewInfo> {
  const _ViewInfoReader();

  @override
  ViewInfo createObject(fb.BufferContext bc, int offset) => 
    ViewInfo._(bc, offset);
}

class ViewInfoBuilder {
  ViewInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ViewInfoObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;

  ViewInfoObjectBuilder({
    int? id,
    String? name,
  })
      : _id = id,
        _name = name;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    fbBuilder.startTable(2);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
