# Extensions: builds every extension directory in LE_EXTENSION_DIRS into this
# build (docs/EXTENSION_MECHANISM_RESEARCH.md §2-3). Included by
# CMakeLists.txt after the `api` and `le::extension_sdk` targets exist.
#
# Each directory's le_extension.toml is read and checked by
# codegen.extension_manifest (identity, compatibility with this build,
# dependencies), which also orders them. A compiled extension's
# le_extension.cmake then calls le_add_extension() with its build details.
# The result is the `le_extensions` library: every extension's core library
# plus a generated register_all(), linked into le_shell and le_tcl.

# le_add_extension(<name>
#     CORE_SOURCES <file>...     the extension's C++, including le_ext_<name>_register
#     [CORE_INCLUDE <dir>...]    public include directories
#     [TESTS <file>...]          GoogleTest sources, built as <name>_tests
#     [LINK <target>...])        the extension's own third-party dependencies
# Paths are relative to the extension directory.
function(le_add_extension name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "CORE_SOURCES;CORE_INCLUDE;TESTS;LINK")
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "le_add_extension(${name}): unknown arguments ${ARG_UNPARSED_ARGUMENTS} "
            "(supported: CORE_SOURCES CORE_INCLUDE TESTS LINK)")
    endif()
    if(NOT name STREQUAL LE_CURRENT_EXTENSION)
        message(FATAL_ERROR "le_add_extension(${name}) called from ${LE_CURRENT_EXTENSION}'s le_extension.cmake - "
            "the name must match its le_extension.toml")
    endif()
    if(NOT ARG_CORE_SOURCES)
        message(FATAL_ERROR "le_add_extension(${name}): CORE_SOURCES is required (at least le_ext_${name}_register)")
    endif()
    set(dir "${LE_EXTENSION_${name}_DIR}")
    list(TRANSFORM ARG_CORE_SOURCES PREPEND "${dir}/")
    list(TRANSFORM ARG_CORE_INCLUDE PREPEND "${dir}/")

    add_library(${name}_core STATIC ${ARG_CORE_SOURCES})
    target_include_directories(${name}_core PUBLIC ${ARG_CORE_INCLUDE})
    target_link_libraries(${name}_core PUBLIC le::extension_sdk ${ARG_LINK})

    if(ARG_TESTS)
        list(TRANSFORM ARG_TESTS PREPEND "${dir}/")
        add_executable(${name}_tests ${ARG_TESTS})
        # le_extensions (defined below) holds every core plus register_all().
        target_link_libraries(${name}_tests PRIVATE le_extensions GTest::gtest_main)
        gtest_discover_tests(${name}_tests)
    endif()
endfunction()

execute_process(
    COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=${CMAKE_CURRENT_SOURCE_DIR}/codegen
        ${Python3_EXECUTABLE} -m codegen.extension_manifest
        --layout-engine-version ${PROJECT_VERSION}
        --extension-api ${LE_EXTENSION_API_VERSION}
        --output ${CMAKE_BINARY_DIR}/le_extension_manifests.cmake
        ${LE_EXTENSION_DIRS}
    RESULT_VARIABLE manifest_result
    ERROR_VARIABLE manifest_errors)
if(NOT manifest_result EQUAL 0)
    message(FATAL_ERROR "LE_EXTENSION_DIRS: ${manifest_errors}")
endif()
include(${CMAKE_BINARY_DIR}/le_extension_manifests.cmake)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/codegen/codegen/extension_manifest.py)

set(le_extension_cores "")
set(le_extension_declarations "")
set(le_extension_registrations "")
foreach(name IN LISTS LE_EXTENSIONS)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${LE_EXTENSION_${name}_MANIFEST})
    if(LE_EXTENSION_${name}_SCHEMA)
        message(FATAL_ERROR "extension ${name}: extension schemas aren't supported yet (#74)")
    endif()
    string(APPEND le_extension_registrations
        "    registry().add({\"${name}\", \"${LE_EXTENSION_${name}_VERSION}\"});\n")
    if(LE_EXTENSION_${name}_CMAKE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${LE_EXTENSION_${name}_CMAKE})
        set(LE_CURRENT_EXTENSION ${name})
        include(${LE_EXTENSION_${name}_CMAKE})
        if(NOT TARGET ${name}_core)
            message(FATAL_ERROR "extension ${name}: ${LE_EXTENSION_${name}_CMAKE} must call le_add_extension(${name} ...)")
        endif()
        list(APPEND le_extension_cores ${name}_core)
        string(APPEND le_extension_declarations "void le_ext_${name}_register(le::ext::Registry &);\n")
        string(APPEND le_extension_registrations "    le_ext_${name}_register(registry());\n")
    endif()
    message(STATUS "Extension ${name} ${LE_EXTENSION_${name}_VERSION} (${LE_EXTENSION_${name}_DIR})")
endforeach()
unset(LE_CURRENT_EXTENSION)

# register_all(): each extension's info, then its register function, in
# dependency order. Written only when it changes, so a reconfigure doesn't
# rebuild it.
set(le_extensions_init "${CMAKE_BINARY_DIR}/generated/le_extensions_init.cpp")
file(CONFIGURE OUTPUT ${le_extensions_init} @ONLY CONTENT [=[
// Generated by cmake/le_extensions.cmake from LE_EXTENSION_DIRS - do not edit.
#include "le/extension.hpp"

@le_extension_declarations@
namespace le::ext
{
    void register_all()
    {
        static bool done = false;
        if (done)
            return;
        done = true;
@le_extension_registrations@    }
}
]=])
add_library(le_extensions STATIC ${le_extensions_init})
target_link_libraries(le_extensions PUBLIC le::extension_sdk ${le_extension_cores})
